version: 2.0.0.{build}

branches:
  only:
    - master

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

before_build:
  - nuget restore .\NCalc2.sln

build:
  project: NCalc2.sln

after_test:
  - ps: .\nuget\pack.ps1

artifacts:
  - path: Evaluant.Calculator\bin\Release\MarkdownLog.dll
    name: NCalc2.dll
  - path: '**\*.nupkg'

#uncomment to publish to NuGet
#deploy:
#  provider: NuGet
#  api_key:
#    secure: n/2gZwCGLcoLBr5nGu5akS0IFQ1YHciI6Wz0NGC+1mLTUtO08Uy+TWn7OtyLG9v3
#  artifact: /.*\.nupkg/
