version: 2.0.1.{build}

branches:
  only:
    - master

environment:
  CoverityProjectToken:
    secure: tgzxkZ3KF15o6qD8VCuG7a2a/uqM87IYTdjC1xF2Hns=
  COVERALLS_REPO_TOKEN:
    secure: B3EbXrtduvUHnLiH1yRBSXzpNUCSdraQo+OD4UdpF/SJKd3qFgWa7Q13/7+ukEBi

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

before_build:
  - nuget restore .\NCalc2.sln

build:
  - cov-build --dir cov-int msbuild /t:Rebuild NCalc2.sln

test_script:
  - ps: .\scripts\test_Script.ps1

after_test:
  - ps: .\scripts\pack.ps1

artifacts:
  - path: Evaluant.Calculator\bin\Release\NCalc2.dll
    name: NCalc2.dll
  - path: '**\NCalc2*.nupkg'
