version: 2.0.0.{build}

branches:
  only:
    - master

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

before_build:
  - nuget restore .\NCalc2.sln

build:
  project: NCalc2.sln

after_test:
  - ps: .\nuget\pack.ps1

artifacts:
  - path: Evaluant.Calculator\bin\Release\NCalc2.dll
    name: NCalc2.dll
  - path: '**\NCalc2*.nupkg'
