version: 2.0.1.{build}

branches:
  only:
    - master

environment:
  COVERITY_TOKEN:
    secure: tgzxkZ3KF15o6qD8VCuG7a2a/uqM87IYTdjC1xF2Hns=
  COVERALLS_TOKEN:
    secure: B3EbXrtduvUHnLiH1yRBSXzpNUCSdraQo+OD4UdpF/SJKd3qFgWa7Q13/7+ukEBi
  EMAIL:
    secure: jVVwtBE/3mg3y/cKt5OL+aX2fX3lHCUO08pdfO1i2SE=

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

before_build:
  - nuget restore .\NCalc2.sln

build:
  project: NCalc2.sln

build_script:
  - ps: .\scripts\build.ps1

test_script:
  - ps: .\scripts\test.ps1

after_test:
  - ps: .\scripts\pack.ps1

artifacts:
  - path: Evaluant.Calculator\bin\Release\NCalc2.dll
  - path: '**\NCalc2*.nupkg'
